---
title:               These aren't the posts you're looking for
tagline:             My cure for Alzheimer's
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Darren Holland
twitter:             putshelloworld
github:              hollanddd
email:               me@darrenholland.com
google_analytics_id: UA-25952752-1
